### ISSUE TITLE
[Errno 2] No such file or directory: 'question_data/interrogative_vocab.data'

### ISSUE THREAD

**Issue by Ailing-Zou** [TobeyYang/S2S_Temp#2]
[Errno 2] No such file or directory: 'question_data/interrogative_vocab.data'
Look forward to your reply!

**Comment by TobeyYang** [comment]
@Ailing-Zou Thanks for your interest.  Please show more details about your ruining commands and arguments. The `interrogative_vocab.data` relates to other attempts and is not utilized in the model, please follow the given command and specify the argument `-no_mask`, thank you.

**Comment by Ailing-Zou** [comment]
ok , if i use the command you give , then there will be no errors. 
thank you
